In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import zscore
from factor_analyzer import FactorAnalyzer

import warnings
warnings.filterwarnings("ignore")

In [3]:
pca_data = pd.read_csv('FB.csv')
pca_data.head()

status_id  num_reactions  num_comments  num_shares  \
0  246675545449582_1649696485147474            529           512         262   
1  246675545449582_1649426988507757            150             0           0   
2  246675545449582_1648730588577397            227           236          57   
3  246675545449582_1648576705259452            111             0           0   
4  246675545449582_1645700502213739            213             0           0   

   num_likes  num_loves  num_wows  num_hahas  num_sads  num_angrys  \
0        432         92         3          1         1           0   
1        150          0         0          0         0           0   
2        204         21         1          1         0           0   
3        111          0         0          0         0           0   
4        204          9         0          0         0           0   

   status_link  status_photo  status_status  
0            0             0              0  
1            0             1              0  
2            0             0              0  
3            0             1              0  
4            0             1              0

In [4]:
pca_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7050 entries, 0 to 7049
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   status_id      7050 non-null   object
 1   num_reactions  7050 non-null   int64 
 2   num_comments   7050 non-null   int64 
 3   num_shares     7050 non-null   int64 
 4   num_likes      7050 non-null   int64 
 5   num_loves      7050 non-null   int64 
 6   num_wows       7050 non-null   int64 
 7   num_hahas      7050 non-null   int64 
 8   num_sads       7050 non-null   int64 
 9   num_angrys     7050 non-null   int64 
 10  status_link    7050 non-null   int64 
 11  status_photo   7050 non-null   int64 
 12  status_status  7050 non-null   int64 
dtypes: int64(12), object(1)
memory usage: 716.1+ KB


In [5]:
pca_data.describe().T

count        mean         std  min   25%   50%     75%  \
num_reactions  7050.0  230.117163  462.625309  0.0  17.0  59.5  219.00   
num_comments   7050.0  224.356028  889.636820  0.0   0.0   4.0   23.00   
num_shares     7050.0   40.022553  131.599965  0.0   0.0   0.0    4.00   
num_likes      7050.0  215.043121  449.472357  0.0  17.0  58.0  184.75   
num_loves      7050.0   12.728652   39.972930  0.0   0.0   0.0    3.00   
num_wows       7050.0    1.289362    8.719650  0.0   0.0   0.0    0.00   
num_hahas      7050.0    0.696454    3.957183  0.0   0.0   0.0    0.00   
num_sads       7050.0    0.243688    1.597156  0.0   0.0   0.0    0.00   
num_angrys     7050.0    0.113191    0.726812  0.0   0.0   0.0    0.00   
status_link    7050.0    0.008936    0.094115  0.0   0.0   0.0    0.00   
status_photo   7050.0    0.608227    0.488181  0.0   0.0   1.0    1.00   
status_status  7050.0    0.051773    0.221584  0.0   0.0   0.0    0.00   

                   max  
num_reactions   4710.0  
num_comments   20990.0  
num_shares      3424.0  
num_likes       4710.0  
num_loves        657.0  
num_wows         278.0  
num_hahas        157.0  
num_sads          51.0  
num_angrys        31.0  
status_link        1.0  
status_photo       1.0  
status_status      1.0

In [7]:
pca_data_new = pca_data.drop(['status_id'],axis= True)
df_scalled = pca_data_new.apply(zscore)
df_scalled

num_reactions  num_comments  num_shares  num_likes  num_loves  num_wows  \
0          0.646104      0.323350    1.686879   0.482727   1.983266  0.196196   
1         -0.173192     -0.252206   -0.304144  -0.144720  -0.318454 -0.147879   
2         -0.006738      0.013089    0.129017  -0.024571   0.206938 -0.033187   
3         -0.257499     -0.252206   -0.304144  -0.231495  -0.318454 -0.147879   
4         -0.037003     -0.252206   -0.304144  -0.024571  -0.093286 -0.147879   
...             ...           ...         ...        ...        ...       ...   
7045      -0.305057     -0.252206   -0.304144  -0.280445  -0.318454 -0.147879   
7046      -0.462863     -0.252206   -0.304144  -0.447319  -0.293436 -0.147879   
7047      -0.493128     -0.252206   -0.304144  -0.476244  -0.293436 -0.147879   
7048       0.261316     -0.238717   -0.136959   0.298053  -0.268417 -0.147879   
7049      -0.460702     -0.252206   -0.304144  -0.440644  -0.318454 -0.147879   

      num_hahas  num_sads  num_angrys  status_link  status_photo  \
0      0.076713  0.473570   -0.155748    -0.094957     -1.245993   
1     -0.176010 -0.152587   -0.155748    -0.094957      0.802573   
2      0.076713 -0.152587   -0.155748    -0.094957     -1.245993   
3     -0.176010 -0.152587   -0.155748    -0.094957      0.802573   
4     -0.176010 -0.152587   -0.155748    -0.094957      0.802573   
...         ...       ...         ...          ...           ...   
7045  -0.176010 -0.152587   -0.155748    -0.094957      0.802573   
7046   0.076713 -0.152587   -0.155748    -0.094957      0.802573   
7047  -0.176010 -0.152587   -0.155748    -0.094957      0.802573   
7048  -0.176010 -0.152587   -0.155748    -0.094957      0.802573   
7049  -0.176010 -0.152587   -0.155748    -0.094957      0.802573   

      status_status  
0         -0.233666  
1         -0.233666  
2         -0.233666  
3         -0.233666  
4         -0.233666  
...             ...  
7045      -0.233666  
7046      -0.233666  
7047      -0.233666  
7048      -0.233666  
7049      -0.233666  

[7050 rows x 12 columns]

In [8]:
from sklearn.decomposition import PCA

In [30]:
pca = PCA(n_components=6,random_state=123)
pca_score = pca.fit_transform(df_scalled)
pca_score

array([[ 2.49500294, -0.18957102, -0.42293659,  0.10348893, -0.07067992,
        -0.76515049],
       [-0.80644199,  0.00767383,  0.60872631, -0.0387954 ,  0.0319256 ,
         0.01663126],
       [ 0.38778102, -0.15966981, -0.62573078,  0.14519118, -0.30187144,
        -0.40336141],
       ...,
       [-0.97231247, -0.40295527,  0.53914638, -0.03771913, -0.03160793,
         0.07582711],
       [-0.46550736,  0.50925543,  0.70494912, -0.03183178,  0.09656654,
        -0.10224415],
       [-0.96536827, -0.35632615,  0.54524478, -0.0385818 , -0.02182985,
         0.06974368]])

In [27]:
pca.explained_variance_

array([3.596288  , 1.78479109, 1.2511225 , 1.02089676, 0.95528279,
       0.84959164])

In [28]:
pca.explained_variance_ratio_

array([0.29964816, 0.14871149, 0.10424542, 0.08506266, 0.07959561,
       0.07078926])

In [31]:
lstNumeric = list(pca_data.select_dtypes(exclude='object').columns)
df_pca_loading = pd.DataFrame(pca.components_,columns=list(lstNumeric))
df_pca_loading

num_reactions  num_comments  num_shares  num_likes  num_loves  num_wows  \
0       0.293631      0.347498    0.443254   0.251770   0.461255  0.296340   
1       0.606641     -0.230746   -0.204910   0.640654  -0.165917  0.016262   
2       0.112002     -0.087548   -0.003929   0.105702   0.051816  0.211549   
3       0.001046     -0.015957    0.034839  -0.001738   0.033363  0.033752   
4       0.081891      0.186288   -0.069866   0.102090  -0.139427 -0.377299   
5      -0.085207     -0.437540   -0.196741  -0.096696  -0.004870  0.372249   

   num_hahas  num_sads  num_angrys  status_link  status_photo  status_status  
0   0.308854  0.163131    0.237247    -0.001383     -0.232614       0.013797  
1  -0.139033 -0.110415   -0.126874     0.064185      0.036551       0.213189  
2   0.101801 -0.049879    0.089232    -0.235213      0.643419      -0.656535  
3   0.017801 -0.252066   -0.042459     0.892600     -0.071887      -0.358771  
4  -0.134292  0.816405    0.123557     0.209968      0.111486      -0.158614  
5   0.057700  0.173121    0.669843     0.190214      0.120870       0.286124

In [33]:
pca = PCA(n_components=12,random_state=123)
pca_score = pca.fit_transform(df_scalled)
pca_score[1]

array([-8.06441994e-01,  7.67382622e-03,  6.08726314e-01, -3.87953990e-02,
        3.19255998e-02,  1.66312578e-02, -4.24094161e-02,  3.94963671e-02,
        2.80764310e-01, -1.02988456e-01, -6.47721649e-03, -4.70029254e-06])