In [2]:
value = 17
for i in range(1,11):
    print(value,"*",i,"=",i * value,)


17 * 1 = 17
17 * 2 = 34
17 * 3 = 51
17 * 4 = 68
17 * 5 = 85
17 * 6 = 102
17 * 7 = 119
17 * 8 = 136
17 * 9 = 153
17 * 10 = 170


In [5]:
cities = ['Delhi','Pune','Mumbai','Hyderabad','Bangalore']
for city in cities:
    if(city == 'pune'):
        print('Its cloudy in pune')
    elif(city == 'Mumbai'):
        print('Its Raining in Mumbai')
    else:
        print('Not sure about the climat in',city)


Not sure about the climat in Delhi
Not sure about the climat in Pune
Its Raining in Mumbai
Not sure about the climat in Hyderabad
Not sure about the climat in Bangalore


In [7]:
def sum(arg1,arg2):
    print('sum of',arg1," and ", arg2,'is', arg1 + arg2)

sum(5,10)


sum of 5  and  10 is 15


In [9]:
def func1(number):
    if(number <= 10):
        return number ** 3
    else:
        return number ** 2
    
print('output is', func1(18))
print('output is', func1(3))

output is 324
output is 27


In [10]:
d1 = {'A':'Alpha','B':'Bita','C':'Gamma'}

In [11]:
type(d1)

dict

In [19]:
L1 = list(d1.items())

In [14]:
L1

['A', 'B', 'C']

In [15]:
L2 = []

In [17]:
for data in d1:
    print(data)

A
B
C


In [20]:
for data in d1:
    print(d1[data])

Alpha
Bita
Gamma


In [26]:
for data in d1:
    L2.append(data)
    L2.append(d1[data])
print(L2)

L2.clear()


['A', 'Alpha', 'B', 'Bita', 'C', 'Gamma']


In [27]:
d1.items()


dict_items([('A', 'Alpha'), ('B', 'Bita'), ('C', 'Gamma')])

In [28]:
list(d1.items())

[('A', 'Alpha'), ('B', 'Bita'), ('C', 'Gamma')]

In [29]:
list(d1.items())[0]

('A', 'Alpha')

In [30]:
list(d1.items())[0][0]

'A'

In [33]:
import numpy as np

arr = np.arange(1,9).reshape(2,4)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
b = np.arange(1,101).reshape(10,10)
b

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [46]:
for i in b:
    print(i[1])

2
12
22
32
42
52
62
72
82
92


In [47]:
b[:,1]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [49]:
b[:,1:5]

array([[ 2,  3,  4,  5],
       [12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45],
       [52, 53, 54, 55],
       [62, 63, 64, 65],
       [72, 73, 74, 75],
       [82, 83, 84, 85],
       [92, 93, 94, 95]])

In [51]:
np.random.randint(1,51,size = 5)


array([ 6, 20, 16, 33,  8])

In [52]:
np.random.randint(1,51,5)

array([27, 49, 19,  8,  5])

In [53]:
np.random.seed(0)
np.random.randint(1,51,5)

array([45, 48,  1,  4,  4])

In [54]:
np.random.randn(10)


array([ 0.37025538,  1.04053075, -1.51698273, -0.86627621, -0.05503512,
       -0.10731045,  1.36546718, -0.09769572, -2.42595457, -0.4530558 ])