In [2]:
import numpy as np

In [4]:
print(np.cos(np.pi))

-1.0


In [6]:
print(np.sqrt(1.21))

1.1


In [8]:
print(np.log(np.exp(5.2)))

5.2


In [10]:
vec = np.array([1,2,3])
print(vec)

[1 2 3]


In [11]:
print(vec.ndim)

1


In [14]:
vec2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(vec2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(vec2.ndim)

2


In [17]:
print(vec2.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [18]:
v1 = np.arange(0,10)
print(v1)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
v2 = np.arange(0,10,2)
print(v2)

[0 2 4 6 8]


In [30]:
v3 = np.linspace(0,5,10)
print(v3)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [31]:
print(v3.reshape(5,2))

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [22]:
v4 = np.zeros([5,3])
print(v4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
v5 = np.zeros((5,3),dtype = int)
print(v5)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [25]:
v6 = np.eye(3,dtype = int)
print(v6)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [35]:
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [36]:
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]



In [37]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [38]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [39]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [43]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(5,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.72711382 0.12942979 0.44392143 0.24593311 0.05398943]
 [0.58974553 0.44143836 0.48505046 0.23335714 0.1560893 ]
 [0.65051567 0.44149573 0.70053157 0.71101895 0.84390657]
 [0.83376109 0.09411626 0.78408068 0.27176982 0.69739741]
 [0.43502471 0.85795965 0.52615281 0.1246651  0.31163295]]

[[-0.34454474  0.26581678  1.86751441 -0.30389427  0.60759846]
 [-0.47936073 -1.31684046 -0.30981023 -0.84732604 -0.06357283]
 [ 0.4823597  -0.94413261  1.41212494 -0.29921149 -1.07145373]
 [-1.60196691 -0.23869879 -1.14871877  0.40288077  1.23961883]
 [-0.98322351  0.99287294  0.58363487  1.30136729 -0.96828179]]


In [44]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.47160389308285205
0.9320402945934241


In [45]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.05398942528932593
1.8675144085828932


In [46]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-0.91867517  2.37216133 -1.48796191  1.04443217  1.30806574 -0.0734824
  2.38385446  1.08997536  1.50975178  1.01108028 -0.1153499  -0.83020256
  0.10920083  0.91882473 -0.41646858  0.23188407  0.80872582 -0.45531753
 -0.80491733]
2.383854459702975


In [47]:
print(rand_vec[2:5])

[-1.48796191  1.04443217  1.30806574]


In [50]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,10,3))
print(rand_vec[np.arange(0,10,3)])

[0 3 6 9]
[-0.91867517  1.04443217  2.38385446  1.01108028]


In [51]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])

[[0.72711382 0.12942979 0.44392143 0.24593311 0.05398943]
 [0.58974553 0.44143836 0.48505046 0.23335714 0.1560893 ]
 [0.65051567 0.44149573 0.70053157 0.71101895 0.84390657]
 [0.83376109 0.09411626 0.78408068 0.27176982 0.69739741]
 [0.43502471 0.85795965 0.52615281 0.1246651  0.31163295]]
0.48505046225136006
0.48505046225136006


In [54]:
print(rand_mat[0:2,1:3])

[[0.12942979 0.44392143]
 [0.44143836 0.48505046]]


In [53]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-0.91867517  2.37216133 -1.48796191  1.04443217  1.30806574 -0.0734824
  2.38385446  1.08997536  1.50975178  1.01108028 -0.1153499  -0.83020256
  0.10920083  0.91882473 -0.41646858  0.23188407  0.80872582 -0.45531753
 -0.80491733]

[-0.91867517  2.37216133 -1.48796191  4.          4.         -0.0734824
  2.38385446  1.08997536  1.50975178  1.01108028 -0.1153499  -0.83020256
  0.10920083  0.91882473 -0.41646858  0.23188407  0.80872582 -0.45531753
 -0.80491733]

[-0.91867517  2.37216133 -1.48796191  1.          2.         -0.0734824
  2.38385446  1.08997536  1.50975178  1.01108028 -0.1153499  -0.83020256
  0.10920083  0.91882473 -0.41646858  0.23188407  0.80872582 -0.45531753
 -0.80491733]


In [57]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.72711382 0.12942979 0.44392143 0.24593311 0.05398943]
 [0.58974553 0.44143836 0.         0.         0.        ]
 [0.65051567 0.44149573 0.         0.         0.        ]
 [0.83376109 0.09411626 0.78408068 0.27176982 0.69739741]
 [0.43502471 0.85795965 0.52615281 0.1246651  0.31163295]]

[[0.72711382 0.12942979 0.44392143 0.24593311 0.05398943]
 [0.58974553 0.44143836 0.         0.         0.        ]
 [0.65051567 0.44149573 0.         0.         0.        ]
 [0.83376109 0.09411626 0.78408068 0.27176982 0.69739741]
 [0.43502471 0.85795965 0.52615281 0.1246651  0.31163295]]
