In [1]:
import numpy as np

In [2]:
demo_array=np.arange(0,10) 

In [3]:
demo_array <3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [4]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

In [5]:
demo_matrix

array([[13, 35, 74, 48],
       [23, 37, 37, 38],
       [73, 39, 93, 39]])

In [6]:
demo_matrix[:, (1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [7]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix

array([[13, 35, 74, 48],
       [23, 37, 37, 38],
       [73, 39, 93, 39]])

In [8]:
demo_matrix[2,3]

39

In [10]:
demo_array = np.arange(10,21)

subset_demo_array = demo_array[0:7]

subset_demo_array[:]= 101

subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [11]:
test_array = [10, 11.5, 12, 13.5, 14,15]   
test_array[2:3]

[12]

In [12]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [15]:
list_l =[[12,34,55,],[66,45,77],[45,77,88]]

v2 = np.array(list_l)
v2

array([[12, 34, 55],
       [66, 45, 77],
       [45, 77, 88]])

In [16]:
v2.ndim

2

In [17]:
i = 1
while i < 6:
    if i%2==0:
        print(i)
    i += 1

2
4


In [18]:
for i in range(2,10,2):

    print(i)

2
4
6
8
