# List: 

**Create a list. Name of the list is List1** 

List1 = ['hello','great','learning']  
   
    
 
   .
   

In [28]:
List1 = ['hello','great','learning']

#####  A.  Repetition(*) - Make  a new list (List2) which contains  all the elements of List1 repeated 2 times.

Hint: use (*2) to create List2

In [29]:
List2 = List1 * 2
List2

['hello', 'great', 'learning', 'hello', 'great', 'learning']

##### B. Concatenation(+): Concate  List1 = ['hello','great','learning']  and List3 = [1,2,3,4] to create List4
**output should be** ['hello', 'great', 'learning', 1, 2, 3, 4]

Hint: To create List4 use (+)

In [30]:
List1 = ['hello','great','learning']
List3 = [1,2,3,4]
List4 = List1 + List3
List4

['hello', 'great', 'learning', 1, 2, 3, 4]

#####    C. Membership - Check whether "Hello" is present in the List1 or not. Output must be True or False

In [31]:
'Hello' in List1

False

#####  D. Length - Check the length of the LIST1. Output must be numeric

In [32]:
len(List1)

3

#####  E. Iteration - print the List1 three times using For loop.

In [33]:
for i in range(0,3):
    print(List1)

['hello', 'great', 'learning']
['hello', 'great', 'learning']
['hello', 'great', 'learning']


##### F. Print  all the elements of List1 separately.

In [34]:
for i in List1:
    print(i)

hello
great
learning


##### G. Create the list(List1 = [15, 300, 2700, 821, 27, 99]) and find
A.	maximum value in the list.	   
B.	minimum value in the list. 

                    
      	

In [35]:
List1 = [15, 300, 2700, 821, 27, 99]
print('maximum value in the list: ',max(List1))
print('minimum value in the list: ',min(List1))

maximum value in the list:  2700
minimum value in the list:  15


##### H.  Append "C" in the List = ['Python','Ml','Sql', 'Stats', 'R'] .

Output must be: ['Python', 'Ml', 'Sql', 'Stats', 'R', 'C']

In [36]:
List = ['Python','Ml','Sql', 'Stats', 'R'] 
List.append('c')
List

['Python', 'Ml', 'Sql', 'Stats', 'R', 'c']

##### I.  Replace "SQL" with "Tableau" in  List = ['Python','Ml','Sql', 'Stats', 'R','C'] .

In [37]:
List[2] = 'Tableau'
List

['Python', 'Ml', 'Tableau', 'Stats', 'R', 'c']

##### J. Add "SQL"  back in the list ['Python', 'Ml', 'Tableau', 'Stats', 'R', 'C'] without replacing any element of the list

In [38]:
List.insert(2,'SQL')
List

['Python', 'Ml', 'SQL', 'Tableau', 'Stats', 'R', 'c']

##### K. Count the number of times "i" appears in the List = ['a', 'e', 'i', 'o', 'i', 'u','y','w','tre','ytre','uyt']. 

Hint: Use List.count(), Output must be numeric.

In [39]:
List = ['a', 'e', 'i', 'o', 'i', 'u','y','w','tre','ytre','uyt']
List.count('i')

2

##### L. Pop/Delete the 3rd indexed element from the  List = ['a', 'e', 'i', 'o', 'i', 'u','y','w','tre','ytre','uyt'].                                      3rd indexed element is "o"

Output must be: ['a', 'e', 'i', 'i', 'u', 'y', 'w', 'tre', 'ytre', 'uyt']

In [ ]:
List = ['a', 'e', 'i', 'o', 'i', 'u','y','w','tre','ytre','uyt']
poped_element = List.pop('o')
print('poped_element',)

# Conditional Statements

##### A. Print  '13 is less than 25' if 13 < 25. 

Hint: Use "If" Statement

In [40]:
if(13 < 25):
    print('13 is less than 25')

13 is less than 25


##### B.  Write a if else  statement to find if the number in the List=[2,10,64,75,15] which are divisible by 5?

Hint: Use "For" loop and "If" Statement

In [41]:
List=[2,10,64,75,15]
for i in List:
    if(i % 5 == 0):
        print(i, 'is divisible by 5')
    else:
        print(i, 'is not divisible by 5')

2 is not divisible by 5
10 is divisible by 5
64 is not divisible by 5
75 is divisible by 5
15 is divisible by 5


##### C. Using the three variables 'a = 289; b = 2300; c = 3900', 
**Write a If...Elif...Else statement to find the greatest number**

Hint: use "&" while defining 2 conditions in the (If,elif) Statement 


In [43]:
a = 289; b = 2300; c = 3900;
if(a > b) and (a > c):
    print(a, 'is Greatest number')
elif(b > c):
    print(b, 'is Greatest number')
else:
    print(c, 'is Greatest number')

3900 is Greatest number


##### D. 1. Write a code to print numbers in range of (10,20) including both(10 and 20) using while loops

In [44]:
i = 10
while(i <= 20):
    print(i)
    i += 1

10
11
12
13
14
15
16
17
18
19
20


# Array

##### A. Create a two dimensional array with values from 1 to 4, numbers to be use row wise also check the dimensions( use .ndim)

In [1]:
import numpy as np

In [3]:
array = np.arange(1,5).reshape(2,2)
array.ndim

2

##### B. Display Maximum and Minimum values in the above array.


In [5]:
print('min value is', array.min())
print('max value is', array.max())

min value is 1
max value is 4


##### C. Check the size and shape of above array:

In [7]:
print('size of arry is',array.size)
print('Shape of array is', array.shape)

size of arry is 4
Shape of array is (2, 2)


##### D. Create an array a=np.array([[1,2],[3,4],[5,6]]). Reshape it to the shape(2,3)

In [11]:
a = np.array([[1,2],[3,4],[5,6]])
a2 = a.reshape(2,3)
a2

array([[1, 2, 3],
       [4, 5, 6]])

##### E.  Create a one(1) value array with shape(4,5)(all the values as 1). Use np.ones()

In [14]:
a3 = np.ones([4,5],dtype= int)
a3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

##### 7. Check variance, standard deviation, mean of an array. 

**x=np.array([[1,2],[3,4],[5,6],[7,8]])**


Hint: use (.std(), .mean(), .var())

In [15]:
x=np.array([[1,2],[3,4],[5,6],[7,8]])
x.std()

In [17]:
x.mean()

4.5

In [18]:
x.var()

5.25

##### 8. Make an array d2.

**d2 = np.array([[1,2,3],[4,5,6],[7,8,9]])**

##### A. Print the element from 1st row  and 1st column i.e 1
##### B. Print the element from 3rd row and 2nd column i.e 8 
##### C. Print all the row elements from col 2 and col 3


**Note: python indexing starts from 0**

In [19]:
d2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
print('d2[0,0]: ',d2[0,0])

d2[0,0]:  1


In [22]:
print('d2[2,1]: ',d2[2,1])

d2[2,1]:  8


In [27]:
print(d2)
print(d2[:, 1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
